objects:
  - name: banana
    loader: ycb
    urdf: 011_banana
    basePosition:
      - [0.45, -0.35, 0.025]
      - [0.55, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: plate
    loader: ycb
    urdf: 029_plate
    globalScaling: 0.8
    basePosition: 
      - [0.9, 0.3, 0.2]
      - [0.7, -0.1, 0.2]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: false
