objects:
  - name: pan
    loader: ycb
    urdf: 029_plate
    globalScaling: 0.8
    basePosition: 
      - [0.9, -0.3, 0.075]
      - [0.7, -0.3, 0.075]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: false

  - name: food
    loader: ycb
    urdf: 007_tuna_fish_can
    basePosition:
      - [0.45, -0.3, 0.025]
      - [0.45, -0.3, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: stove
    loader: collab
    urdf: microwave
    basePosition: 
      - [0.8, 0.3, 0.1]
      - [0.8, 0.1, 0.1]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true