objects:
  - name: bowl
    loader: ycb
    urdf: 024_bowl
    basePosition:
      - [0.45, -0.25, 0.025]
      - [0.45, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: food
    loader: ycb
    urdf: 015_peach
    basePosition:
      - [0.45, -0.25, 0.03]
      - [0.45, -0.25, 0.03]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: microwave
    loader: collab
    urdf: microwave
    basePosition: 
      - [0.8, 0.2, 0.125]
      - [0.9, -0.1, 0.125]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true