objects:
  - name: banana
    loader: ycb
    urdf: 011_banana
    basePosition:
      - [0.45, -0.35, 0.025]
      - [0.55, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: peach
    loader: ycb
    urdf: 015_peach
    basePosition: [0.25, -0.45, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: orange
    loader: ycb
    urdf: 017_orange
    basePosition:
      - [0.25, 0.175, 0.025]
      - [0.25, 0.175, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: apple
    loader: ycb
    urdf: 013_apple
    basePosition:
      - [0.25, 0.175, 0.025]
      - [0.25, 0.175, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: lemon
    loader: ycb
    urdf: 014_lemon
    basePosition:
      - [0.25, 0.175, 0.025]
      - [0.25, 0.175, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false