objects:
  - name: cube1
    loader: simple
    urdf: cube
    basePosition:
      - [0.45, -0.35, 0.025]
      - [0.55, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: cube2
    loader: simple
    urdf: cube
    basePosition:
      - [0.55, 0.0, 0.025]
      - [0.65, 0.0, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: rubikscube1
    loader: ycb
    urdf: 077_rubiks_cube
    basePosition:
      - [0.6, 0.175, 0.025]
      - [0.7, 0.175, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: rubikscube2
    loader: ycb
    urdf: 077_rubiks_cube
    basePosition:
      - [0.7, -0.175, 0.025]
      - [0.8, -0.175, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false