objects:
  - name: emptybox
    loader: ycb
    urdf: 003_cracker_box
    basePosition:
      - [0.55, -0.25, 0.025]
      - [0.65, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: emptycan
    loader: ycb
    urdf: 007_tuna_fish_can
    basePosition: [0.75, 0.0, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: emptysugarbox
    loader: ycb
    urdf: 004_sugar_box
    basePosition:
      - [0.45, 0.1, 0.025]
      - [0.45, 0.2, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: trashcan
    loader: ycb
    urdf: 065-a_cups
    globalScaling: 0.6
    basePosition: 
      - [0.6, -0.75, -0.45]
      - [0.6, -0.75, -0.45]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true