objects:
  - name: sponge
    loader: ycb
    urdf: 026_sponge
    basePosition:
      - [0.45, -0.35, 0.020]
      - [0.55, -0.25, 0.020]
    baseOrientationEuler:
      - [0.0, 1.57, 0.0]
      - [0.0, 1.57, 3.141592653]
    useFixedBase: false

  - name: plate
    loader: ycb
    urdf: 029_plate
    globalScaling: 0.8
    basePosition: 
      - [0.9, 0.3, 0.075]
      - [0.7, -0.1, 0.075]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true