tasks:
  - "clean_up_the_table"
  - "close_the_bottle"
  - "cook_the_food_using_the_microwave"
  - "cook_the_food_using_the_stove"
  - "empty_the_cabinet"
  - "empty_the_fridge"
  - "make_coffee"
  - "make_toast"
  - "move_the_lonely_object_to_the_others"
  - "move_the_right_can_to_the_left_can"
  - "open_fridge"
  - "open_the_bottle"
  - "pick_the_left_can"
  - "pour_the_can"
  - "put_food_in_fridge"
  - "put_the_banana_on_the_plate"
  - "put_the_cube_away"
  - "put_the_food_away"
  - "put_the_food_in_the_microwave"
  - "put_the_food_in_the_pan_and_place_it_in_the_microwave"
  - "put_the_trash_away"
  - "season_the_food"
  - "set_the_table"
  - "stack_the_cubes"
  - "turn_on_the_faucet"
  - "wipe_the_plate"
