tasks:
  - "clean up the table"
  - "cook the food using the microwave"
  - "cook the food using the stove"
  - "empty the fridge"
  - "make toast"
  - "move the lonely object to the others"
  - "move the right can to the left can"
  - "open fridge"
  - "open the bottle"
  - "pick the left can"
  - "put the banana on the plate"
  - "put the cube away"
  - "put the food in the microwave"
  - "put the food in the pan and place it in the microwave"
  - "put the trash away"
  - "season the food"
  - "set the table"
  - "stack the cubes"
  - "turn on the faucet"
  - "wipe the plate"

held_out_tasks:
  - "make coffee"
  - "empty the cabinet"
  - "put food in fridge"
  - "pour the can"
  - "close the bottle"
