tasks:
  - "-clean up the table"
  - "-close the bottle: the golf ball was placed instead of bottle cap."
  - "-open the bottle: the bleach cleanser was placed instead of bottle."
  - "-cook the food using the microwave"
  - "-cook the food using the stove"
  - "-empty the cabinet"
  - "empty the fridge"
  - "fill the fridge"
  - "put food in fridge"
  - "make coffee (keurig):"
  - "make coffee (standard)"
  - "-pour the can"
  - "-make toast"
  - "-put banana on plate"
  - "-put food in microwave"
  - "-put the objects in the pan and place it in the microwave: the tuna can was placed as the food."
  - "-put trash away"
  - "-rearrange the silverware"
  - "-season the food"
  - "-stack the cubes"
  - "-turn on the faucet"
  - "-wipe the plate"
