tasks:
  - "-clean up the table"
  - "-close the bottle: the golf ball was placed instead of bottle cap."
  - "-cook the food using the microwave: there is no button."
  - "-cook the food using the stove: there is no button."
  - "-empty the cabinet"
  - "empty the fridge: the cabinet was placed instead of fridge."
  - "fill the fridge: the cabinet was placed instead of fridge."
  - "make coffee (keurig):"
  - "make coffee (standard)"
  - "make toast"
  - "-open the bottle: the bleach cleanser was placed instead of bottle."
  - "pour the can"
  - "-put banana on plate"
  - "put food in fridge: the cabinet was placed instead of fridge."
  - "-put food in microwave"
  - "-put the objects in the pan and place it in the microwave: the tuna can was placed instead of the food."
  - "-put trash away: the plate was placed instead of the trash can."
  - "-rearrange the silverware"
  - "season the food: the cube was placed instead of salt."
  - "-stack the cubes"
  - "turn on the faucet"
  - "-wipe the plate"
