objects:
  - name: cube
    loader: simple
    urdf: cube
    basePosition:
      - [0.45, -0.15, 0.025]
      - [0.55, -0.05, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: banana
    loader: ycb
    urdf: 011_banana
    basePosition:
      - [0.45, -0.35, 0.025]
      - [0.55, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: peach
    loader: ycb
    urdf: 015_peach
    basePosition: [0.8, -0.35, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: cabinet
    loader: collab
    urdf: cabinet
    basePosition: 
      - [0.8, 0.1, 0.175]
      - [0.9, 0.2, 0.175]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true