objects:
  - name: soupcan
    loader: ycb
    urdf: 005_tomato_soup_can
    basePosition:
      - [0.5, -0.15, 0.025]
      - [0.6, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: meatcan
    loader: ycb
    urdf: 010_potted_meat_can
    basePosition:
      - [0.65, 0.15, 0.025]
      - [0.75, 0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false