objects:
  - name: bowl
    loader: robocasa
    urdf: bowl_4
    basePosition:
      - [0.48, -0.25, 0.025]
      - [0.48, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: sausage
    loader: robocasa
    urdf: hot_dog
    globalScaling: 0.6
    basePosition:
      - [0.48, -0.25, 0.028]
      - [0.48, -0.25, 0.028]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: microwave
    loader: collab
    urdf: microwave
    basePosition: 
      - [0.8, 0.2, 0.175]
      - [0.85, 0.0, 0.175]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true