objects:
  - name: food
    loader: ycb
    urdf: 007_tuna_fish_can
    basePosition:
      - [0.35, 0.0, 0.025]
      - [0.40, 0.0, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: fridge
    loader: collab
    urdf: fridge
    basePosition: [0.8, 0.2, 0.0]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true