objects:
  - name: cube
    loader: simple
    urdf: cube
    basePosition:
      - [0.74, -0.10, 0.19]
      - [0.77, -0.07, 0.19]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: banana
    loader: ycb
    urdf: 011_banana
    basePosition:
      - [0.74, 0.05, 0.19]
      - [0.77, 0.08, 0.19]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: peach
    loader: ycb
    urdf: 015_peach
    basePosition: 
      - [0.80, -0.05, 0.19]
      - [0.83, -0.02, 0.19]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: fridge
    loader: collab
    urdf: fridge
    basePosition: [0.8, 0.0, 0.17]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true