objects:
  - name: plate
    loader: ycb
    urdf: 029_plate
    globalScaling: 0.8
    basePosition: [0.85, 0.0, 0.075]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true

  - name: fork
    loader: ycb
    urdf: 030_fork
    basePosition:
      - [0.45, 0.0, 0.025]
      - [0.48, 0.0, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: spoon
    loader: ycb
    urdf: 031_spoon
    basePosition:
      - [0.50, -0.35, 0.025]
      - [0.53, -0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false

  - name: knife
    loader: ycb
    urdf: 032_knife
    basePosition:
      - [0.60, 0.35, 0.025]
      - [0.63, 0.25, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 3.141592653]
    useFixedBase: false